### ISSUE TITLE
ValueError('Problem with video writer')Problem with video writer

### ISSUE THREAD

**Issue by ohmaytt** [uyitroa/osr2mp4-app#8] opened 2020-07-12 07:13 UTC
![image](https://user-images.githubusercontent.com/45356936/87241081-75c27380-c45a-11ea-818c-9fd8d2079e08.png)

Seems to happen when rendering with osu! on

**Comment by zabaplays** [comment] 2020-07-12 19:49
had the same error, except happened when i tried to render a replay in 4k resolution, didn't matter whether osu was open or not because also manged to get successful renders with osu open

**Comment by uyitroa** [comment] 2020-07-12 20:28
Please reproduce the error and send logs folder.

**Comment by zabaplays** [comment] 2020-07-12 21:14
[deleteexit.log](https://github.com/uyitroa/osr2mp4-app/files/4909530/deleteexit.log)
[delsettings.log](https://github.com/uyitroa/osr2mp4-app/files/4909531/delsettings.log)
[runosu.log](https://github.com/uyitroa/osr2mp4-app/files/4909532/runosu.log)
[app.log](https://github.com/uyitroa/osr2mp4-app/files/4909533/app.log)

heres the logs that managed to upload

**Comment by uyitroa** [comment] 2020-07-13 14:21
@zabaplays weird, it seems to be an internet connection issue, try disable global leaderboard and try it again.

**Comment by uyitroa** [comment] 2020-07-15 11:45
Update the app if you still encounter this issue. Closing this issue, feel free to open a new issue if the issue still persists.

**Closed by uyitroa** 2020-07-15 11:45 UTC
